### ISSUE TITLE
Compile UE 4.26

### ISSUE THREAD

**Issue by ixsolve** [KTA552/UE-EditorUIScaleCustomization#7]
Great plugin! As the compile process from 4.26 it wont let me compile without any "Category" tag given. I fixed that easily:

UPROPERTY(Category=General, Config, EditAnywhere, BlueprintReadWrite, meta=(ConfigRestartRequired = 1.0f, UIMin=0.5f, UIMax=3.0f))
	float UIScale;

**Comment by KTA552** [comment]
@ixsolve 
Thanks for the issue, I was using 5.x and forgot about that problem. Please wait a bit while we address it.

**Comment by KTA552** [comment]
@ixsolve 
Hi, I have addressed this issue. I hope you can take a look at it when you have time. 
Thanks.

**Comment by ixsolve** [comment]
Great! Thank you, now it can easily compile with 4.26 for everyone that is using it for that version.
